name: 'Run spriggit'
description: 'Runs spriggit tool'
author: 'FlayaN'
inputs:
  dot_spriggit_path:
    description: 'Path to the .spriggit file'
    required: false
    default: .spriggit
  plugin_path:
    description: 'Path to the folder containing the root RecordData.yaml'
    required: true
  output_path:
    description: 'Path to the plugin output'
    required: true
runs:
  using: 'composite'
  steps:

    - name: open .spriggit
      shell: bash
      run: cat ${{ inputs.dot_spriggit_path }}
    
    - name: get spriggit version from .spriggit
      shell: bash
      id: spriggit-version
      run: |
        SPRIGGIT_VERSION=$(grep -oP '(?<="Version": ")[^"]*' ${{ inputs.dot_spriggit_path }})
        echo "SPRIGGIT_VERSION=$SPRIGGIT_VERSION" >> $GITHUB_ENV

    - name: Fetch spriggit
      shell: bash
      run: gh release download -O .github/spriggit.zip -p 'SpriggitLinuxCLI.zip' -R Mutagen-Modding/Spriggit ${{ env.SPRIGGIT_VERSION }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Extract some files
      shell: bash
      run: 7z x .github/spriggit.zip -o.github/spriggit

    - name: fix spriggit permission
      shell: bash
      run: chmod +x .github/spriggit/Spriggit.CLI

    - name: run spriggit
      shell: bash
      run: .github/spriggit/Spriggit.CLI deserialize -i ${{ inputs.plugin_path }} -o ${{ inputs.output_path }}

branding:
  icon: 'tag'
  color: 'gray-dark'
