name: 'Run spriggit'
description: 'Runs spriggit tool'
author: 'FlayaN'
inputs:
  spriggit_tool_version:
    description: 'Version of the spriggit cli to use, defaults to latest'
    required: false
    default: ''
  spriggit_args:
    description: 'Spriggit cli args'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fetch spriggit
      shell: bash
      run: gh release download -O .github/spriggit.zip -p 'SpriggitLinuxCLI.zip' -R Mutagen-Modding/Spriggit ${{ inputs.spriggit_tool_version }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Extract some files
      shell: bash
      run: 7z x ${{ github.workspace }}/.github/spriggit.zip -o${{ github.workspace }}/.github/spriggit

    - name: fix spriggit permission
      shell: bash
      run: chmod +x ${{ github.workspace }}/.github/spriggit/Spriggit.CLI

    - name: run spriggit
      shell: bash
      run: ${{ github.workspace }}/.github/spriggit/Spriggit.CLI ${{ inputs.spriggit_args }}

branding:
  icon: 'tag'
  color: 'gray-dark'
