name: 'Run spriggit'
description: 'Runs spriggit tool'
author: 'FlayaN'
inputs:
  dotspriggitpath:
    description: 'Path to the .spriggit file'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Fetch spriggit
      shell: bash
      run: gh release download --repo Mutagen-Modding/Spriggit 0.5
      env:
        GH_TOKEN: ${{ github.token }}

    - name: See what we downloaded
      shell: bash
      run: ls

branding:
  icon: 'tag'
  color: 'gray-dark'
