name: 'Run spriggit'
description: 'Runs spriggit tool'
author: 'FlayaN'
inputs:
  dot_spriggit_path:
    description: 'Path to the .spriggit file'
    required: false
    default: .spriggit
  plugin_path:
    description: 'Path to the folder containing the root RecordData.yaml'
    required: true
  output_path:
    description: 'Path to the plugin output'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Fetch spriggit
      shell: bash
      run: gh release download -O .github/spriggit.zip -p 'SpriggitLinuxCLI.zip' -R Mutagen-Modding/Spriggit 0.5
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Extract some files
      shell: bash
      run: 7z x .github/spriggit.zip -o.github/spriggit

    - name: See whats on the agent
      shell: bash
      run: ls -a -R .

    - name: open .spriggit
      shell: bash
      run: cat ${{ inputs.dot_spriggit_path }}

    - name: fix spriggit permission
      shell: bash
      run: chmod +x .github/spriggit/Spriggit.CLI

    - name: run spriggit
      shell: bash
      run: .github/spriggit/Spriggit.CLI deserialize -i ${{ inputs.plugin_path }} -o ${{ inputs.output_path }}

    - name: See whats on the agent
      shell: bash
      run: ls -a -R .

branding:
  icon: 'tag'
  color: 'gray-dark'
